version: '3'

services:
  api:
    # image: capizani/projeto-aplicado-api
    build: .
    image: pa-api-image
    container_name: projeto-aplicado-api
    command: python3 main.py
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/api/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

  
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.13.0
    container_name: metricbeat
    user: root
    command: --strict.perms=false -e 
    depends_on:
      - elasticsearch
      - kibana
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.beats/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    restart: on-failure

  
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.13.0
    container_name: heartbeat
    command: --strict.perms=false -e 
    depends_on:
      - elasticsearch
      - kibana
      - metricbeat
      - api
    volumes:      
    - ./.beats/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    environment: 
    - setup.kibana.host=kibana:5601
